<?php

/**
 * @file
 * Contains ws_tenho_interesse.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ws_tenho_interesse_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ws_tenho_interesse module.
    case 'help.page.ws_tenho_interesse':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Módulo de envio de formulário de tenho interesse') . '</p>';
      return $output;

    default:
  }
}